import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  "tutorialSidebar": [

    {
      "type":"category",
      label: '翻译图书',
      link: {type: 'doc', id: 'book-translations'},
      "items":[
        {
          type: 'autogenerated',
          dirName: 'books', // Generate sidebar slice from docs/api
        }
      ]
    },
    {
      "type":"category",
      label: '读书有感',
      link: {type: 'doc', id: 'read-book-feeling'},
      "items":[
        {
          type: 'autogenerated',
          dirName: 'notes',
        }
      ]
    },
  ],
  "apiSidebar":[{
    type: 'autogenerated',
    dirName: 'api', // Generate sidebar slice from docs/api
  }]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
